title: Nhan Nguyen
description: Software Developer | Co-founder Trigger Tracker | BSc '22
baseurl: ""
url: https://nhtnhan.me/

# site settings
taglong: long
tagshort: Software Developer | Co-founder Trigger Tracker | BSc '22

# author settings
author:
  name: Nhan Nguyen
  email: nhtnhan@hotmail.com
photo: assets/files/photo.jpg
address: Edmonton

# social media links
social:
  github: nhtnhan
  linkedin: nhthiennhan

# build settings
permalink: pretty
exclude:
  - docker-compose.yml
  - LICENSE
  - README.md
