title: Nhan Nguyen
description: I am a software developer at LawDepot. I
baseurl: ""
url: https://nhtnhan.me/

# site settings
taglong: Nhan Nguyen
tagshort: Nhan Nguyen

# author settings
author:
  name: Nhan Nguyen
  email: nhtnhan@hotmail.com
photo: assets/files/photo.jpg
address: Edmonton

# social media links
social:
  github: nhtnhan
  linkedin: nhthiennhan

# build settings
permalink: pretty
exclude:
  - docker-compose.yml
  - LICENSE
  - README.md
